### ISSUE TITLE
Can't run: Blank page with: about:blank#blocked

### ISSUE THREAD

**Issue by TheManFromEarth1** [patrikx3/onenote#109]
Version: P3X-OneNote-2020.10.109.AppImage
System: Kubuntu 20.04 with KDE Plasma 5.18.5. Kernel 5.4.0

After you run the AppImage, your stuck in this view:
![image](https://user-images.githubusercontent.com/57072774/89216114-2c34f680-d5ca-11ea-9299-7b51f15b4d13.png)

Older version was working before (last week)

**Comment by TheManFromEarth1** [comment]
Ok I run it with a console once: 

_NODE_ENV=debug ./P3X-OneNote-2020.10.109.AppImage_

First Console the console empty, but then I saw that a top-menu opened after refreshing (ctrl + R) or something.

There I clicked the first menu: 
- Personal Home

This send me to the login page and now it works, even if I restart. 

Seems like there is some cache or expired cookie?
Because I deleted and downloaded the latest AppImage but still got the blank page.

Just so that we can update the "troubleshooting" page.

Also the Top-Menu has disappeared, should it show always? Looked like there were a few options.

**Comment by TheManFromEarth1** [comment]
I tried but couldn't either. 

Still think it could be because the old session timed out, because I hadn't run it in a few days.

**Comment by cppcooper** [comment]
Alt works. I can reproduce this pretty easily, my onenote is full of deleted notebooks (from ~2013/14). I just need to click one, which takes me to onedrive then I can usually click any of the notebooks that appear there and they'll have `about:blank#blocked` as the URI and at that point just need to click internal.

**Comment by cppcooper** [comment]
> my only problem is that i have tons of deleted notebooks but when i click on it it opens nothing:

I get that too sometimes, usually when going in from that screen in your screenshot. Other times it takes me to onedrive, from there I also get a mixed bag. It is there I end up with that blank screen, to clarify though.. I don't have any of the deleted notebooks on onedrive (previously they did exist and didn't open; format difference I think between onenote current and onenote 2013 - I deleted them for this assumption)
