### ISSUE TITLE
JavaScript Error Opening Notebooks

### ISSUE THREAD

**Issue by gomker** [patrikx3/onenote#111]
```Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

![Screenshot from 2020-08-12 11-32-07](https://user-images.githubusercontent.com/3577339/90042224-04135a80-dc90-11ea-8e09-38cf6dea9a8a.png)

Sometimes the above error happens. If I go back and re-select the notebook it usually will load successfully.

**Comment by gomker** [comment]
I did forget to mention my actions - I was chossing "More Notebooks" from the menu, then selecting a different notebook.
It does look like this was a transient error, maybe it was something broken on Microsofts side.

**Comment by gomker** [comment]
This is corporate usage - I will say it doesnt happen after I have switched one time. This may have been a one time glitch when I selected the correct notebook. Feel free to close if you think so as well.

**Comment by j4l-Shvn** [comment]
![image](https://user-images.githubusercontent.com/57270300/90217319-463aba00-ddbe-11ea-8424-92870cd05916.png)

I get the same issue every time I switching apps and trying to return back to a onenote-notebook. I'm on a Ubuntu 18.04 5.4.0-42-generic kernel.

**Comment by j4l-Shvn** [comment]
Yes!! have not tested on a personal account.

**Comment by j4l-Shvn** [comment]
any updates? Any config/cached stuff that I can delete/rearrange to handle this? It seems that I am stuck on this page... Is reinstallation the only way out at this time?

**Comment by gomker** [comment]
@j4l-Shvn  my work around so far is to click "show more in one drive" - use Internal Link
Then click the notebook in one-drive. It will show an error again but it did open the notebook.
Not ideal, but seems to work

**Comment by j4l-Shvn** [comment]
Thanks..@gomker .. i remember doing that once earlier but forgot the exact trick... Found it... Incidentally now I have a different issue... Once I changed my corporate password, I can't log back in, it always refuses to acknowledge my account :).
