### ISSUE TITLE
Add the ability to spawn multiple windows and/or tabs for multiple accounts

### ISSUE THREAD

**Issue by szul** [patrikx3/onenote#112]
Microsoft enables multiple accounts/sign-ins. It would be nice to have the ability to surface OneNote notebooks from different sign-in accounts, even if it's just as simple as being able to run multiple instances of PX3 at once.

**Comment by szul** [comment]
@p3x-robot How do I bring up that menu? Installed on Pop OS (Ubuntu) via Snap, my top menu is blank. No additional controls.

**Comment by szul** [comment]
This could be good enough for me if each windows holds its logged in context. Might be a little cumbersome on each computer restart, but works.

**Comment by andrew-karasev** [comment]
I have a solution (more of a work around), the way to do this is to share an entire notebook with full read/write access, that way you can open multiple instances from multiple accounts
