### ISSUE TITLE
Cant Login to One Note account using a Company/School account 

### ISSUE THREAD

**Issue by snostormjp** [patrikx3/onenote#115]
In Mar 2020 ish used the application to longing to my child's school account, on thier desktop at home, updated version freshly installed on laptop through arch aur and appimage will not allow login to the school account, looking at win10 version of one note noticed that I had to select which type of account, and that when using web based office 365 login seemed to be different url. 
https://login.microsoftonline.com  not the live login url

**Comment by snostormjp** [comment]
Thanks, I will try that if no i will stasrt looking at the code

**Comment by Sabin-Gheorghiu** [comment]
Hey I had the same issue - make sure the time and location on your machine are properly synced - try it in the browser and then back in px3-onenote. 
Manjaro user

**Comment by irby** [comment]
I know this is an old issue, but I did check out with both my work and school accounts, and I was able to log into both accounts fine.

System Info: Linux Mint 20.2 Cinnamon (Cinnamon version 5.0.4 - Linux Kernel 5.4.0-74-generic)
