### ISSUE TITLE
Can't open notebooks from navigation pane

### ISSUE THREAD

**Issue by SuryaThiru** [patrikx3/onenote#116]
I can't seem to switch between notebooks by clicking on them directly in the navigation pane. Sections and pages, on the other hand, work perfectly fine in the navigation pane. I can access the notebook by clicking "More Notebooks" and selecting them from the Notebooks webpage.

I've tried logging out and in, force reloading, clearning cache and reinstalling. Nothing seems to fix the issue.

![ezgif com-crop](https://user-images.githubusercontent.com/22935226/93663976-22d3f080-fa89-11ea-9584-3e2122b0ae26.gif)

Thank you :smile: !

**Comment by Accostic** [comment]
Hi, I am having the same issues as the users above. I understand that reproducibility is an issue, but just wanted to add another vote to this issue. I will see if I can get reproducibility info. I am on Fedora 32 using an enterprise Microsoft account

**Comment by SuryaThiru** [comment]
I am not facing this issue in the latest release (2020.10.178).

**Comment by bpringe** [comment]
Just to add info here. I'm on Manjaro Linux and was having this issue. I clicked a notebook and nothing would happen. I upgraded to v2020.10.164 (latest in AUR repo) by uninstalling and reinstalling, then restarted my machine and it works now.

**Comment by bmarien** [comment]
I had the same issue, but as @bpringe already said, upgrading to the latest version fixes this issue (I also use an 'enterprise' account)
