### ISSUE TITLE
Feature request]: Add Flatpak & deb package

### ISSUE THREAD

**Issue by dtantono** [patrikx3/onenote#130]
it would be great if we could have at hand this app in a Flatpak & deb format.
O.S: Ubuntu
O.S. version: 20.04
version 2021.4.101

**Comment by freddyw** [comment]
I would love a flatpak version as well!

**Comment by freddyw** [comment]
If it can't be a flatpak, would a rpm be possible? I am using Fedora, would be nice.

**Comment by freddyw** [comment]
No worries, I can test it (on Fedora 32 and 33) and let you know the result. Thanks in advance!

**Comment by freddyw** [comment]
Works fine on Fedora 32 and 33. Many thanks!

**Comment by dtantono** [comment]
where is the flatpak link?

**Comment by andreacoi** [comment]
There will be also an official repo in the future?

**Comment by dtantono** [comment]
@p3x-robot it looks like electron builder is supported (https://github.com/electron-userland/electron-builder/issues/512). Can it be reopened?

**Comment by rbarte** [comment]
> If it can't be a flatpak, would a rpm be possible? I am using Fedora, would be nice.

I would also vote for a RPM package (Fedora). ;-)

BUT, the simplest method of distribution are standard Linux distro-indepenent binaries (packed with *.tar.gz). They are convenient for most Linux users - one can just unpack them to  ~/opt (for autoupdate) or /opt, install dependencies and run. Not everyone uses snap/flatpak/appimage. And binary is simplest solution.

**Comment by LeandroStanger** [comment]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing **onenote** on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by dtantono** [comment]
@LeandroStanger the current workaround is use distrobox and install the deb file from within.
