### ISSUE TITLE
KNOWN BUG: Cannot change the Oneline Onenote language UI

### ISSUE THREAD

**Issue by sjx95** [patrikx3/onenote#14]
I selected language before opening my notebook,  
but after my notebook was opened, it still changed to en_US.

I had a look at `~/.config/p3x-onenote`, but didn't find any config file.

Is there someting I ignored?

**Comment by sjx95** [comment]
@p3x-robot This doesn’t work. It changed in current page, but back to English after a open any notebook.
And it’s all right in Google Chrome, even my chrome is in English.

**Comment by sjx95** [comment]
Or maybe I should clean my cache? And I wonder if LANG= will work.
Sorry that I’m not in front of my pc, I’ll have some try tomorrow, about 16 hrs later.

**Comment by Megaman99** [comment]
Can I make Italian translation for this program?
