### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by MajorTomDE** [patrikx3/onenote#198]
It would be nice if there was also a Flatpak version on Flathub.

Thank you
Thomas

**Comment by RayJW** [comment]
It's great to finally see a Flatpak! Thank you :)

Is there something blocking you from publishing it to Flathub or is there anything one can do to help to move that further along? Also, currently the manifest uses a bunch of EOL runtimes, I can open a PR fixing that if there is no particular reason for this.

**Comment by RayJW** [comment]
I'm not super familiar with the process of submitting a Flatpak, either. But I've done a little maintenance work on some before. I think this might help a little further along: https://docs.flatpak.org/en/latest/electron.html

**Comment by MajorTomDE** [comment]
> we are not getting this flathub release as it is a trade marked name and logo, so i can not release on flathub, there is a release manually you can install, but the rest is tm...

Wondering, because there is also on unofficial Teams flatpak:
https://flathub.org/de/apps/com.github.IsmaelMartinez.teams_for_linux
