### ISSUE TITLE
How to set socket proxy?

### ISSUE THREAD

**Issue by ZhangShurong** [patrikx3/onenote#20]
How to set socket proxy?

**Comment by ZhangShurong** [comment]
I want to set a http proxy or sockt proxy to access notebooks, just like
`like this?
PROXY 127.0.0.1:8888; DIRECT`

**Comment by Gabirel** [comment]
Is there any instruction for the proxy? like `socks5://127.0.0.1:1080` or just `127.0.0.1:1080`?

I don't even know whether it's correct since the program doesn't show any errors.

**Comment by bejondshao** [comment]
For later users, click `Settings` -> `Set proxy` and input:

127.0.0.1:8888

no other information
