### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by KarlWebster97** [patrikx3/onenote#3]
http://imgur.com/a/TnXNz

This is a link to my error. I am trying to install this on Fedora 25. I have installed Async and Await. I am still unable to install.

**Comment by Valdenirmezadri** [comment]
Same error

**Comment by Valdenirmezadri** [comment]
error persist
![image](https://user-images.githubusercontent.com/4634624/29026639-1dfc94d0-7b53-11e7-893a-82e8b10ac75c.png)

**Comment by Valdenirmezadri** [comment]
Thanks! now its working!
