### ISSUE TITLE
Is it compatable with Win OneNote?

### ISSUE THREAD

**Issue by GildedHonour** [patrikx3/onenote#32]
Can I move my notes back and forth between Windows OneNote and p3x-OneNote? Are they **fully** compotable?

**Comment by GildedHonour** [comment]
How can that matter? The format of a OneNote file is either compatable with the one of Linux or not, regardless where you save it to.

**Comment by GildedHonour** [comment]
I want to have my notes locally **only**. On Linux and Windows and sync them using physical devices such as USB memory cards. 
I don't want to use a cloud.

Is it impossible with this version?

**Comment by Roller44** [comment]
Forgive my poor English… What do you mean reading up?
________________________________
发送自 Windows 10 版邮件应用

**Comment by GildedHonour** [comment]
@p3x-robot if I use this app, then I connect to my account from Windows OneNote, will I able to download all my data from the cloud so I can use them **locally only** on Windows?
