### ISSUE TITLE
Error "version `NSS_3.22' not found" on start up

### ISSUE THREAD

**Issue by maphew** [patrikx3/onenote#36]
Download and run Sept 28 release:
```
./p3x-onenote-2018.9.28-4-x86_64.AppImage
/tmp/.mount_onenotrardje/p3x-onenote: /usr/lib/x86_64-linux-gnu/libnss3.so: version `NSS_3.22' not found (required by /tmp/.mount_onenotrardje/p3x-onenote)
```

On Linux Mint 18 cinnamon (ubuntu 16.04)

**Comment by Roller44** [comment]
Have you tried "sudo apt-get -f" command? I recommend you to tried it.

**Comment by maphew** [comment]
It's working now. I applied all updates last night pending in Update Manager. Presumably one of them ran `apt install libnss3`

@Roller44 `sudo apt-get -f` tells me "E: Command line option 'f' [from -f] is not understood in combination with the other options.".   I think you probably meant `sudo apt-get --fix-broken install`?
