### ISSUE TITLE
Notebooks column links open an external browsers

### ISSUE THREAD

**Issue by kbumsik** [patrikx3/onenote#42]
Hi,
Firstly thanks for this amazing app. It is very useful for Linux users :)

I found that the links in the Notebooks column in the left side in the below screenshot (hidden by default) opens an external browser.
It would be great if users can open a notebook in this column.

![image](https://user-images.githubusercontent.com/7823583/50440134-1bc19200-0938-11e9-84f5-0e42430c5765.png)

**Comment by kbumsik** [comment]
I mean, it is NOT external URL. The notebooks on the left side opens the notebook via external browser.

**Comment by Andrew5569** [comment]
I think what he is talking about is if you try to open another notebook (after already having one open) it opens in an external browser. 

Some actual urls:

say in a notebook viewing a page:

https://onedrive.live.com/redir?resid=16E189120A1BDF79%2115440&page=Edit&wd=target%28New%20Section%201.one%7C2a1cd553-cd5a-6946-8313-6e1b0e461ddf%2FLecture%201%7C7328759a-b0cc-db40-b86b-6d93cb86e62f%2F%29 

and I try to navigate to another notebook via notebook column:

https://d.docs.live.net/16e189120a1bdf79/Documents/3020h?wdorigin=704

The notebook will open in an external browser.
