### ISSUE TITLE
Non-OneNote links open in app, not browser

### ISSUE THREAD

**Issue by mospaw** [patrikx3/onenote#51]
I'm running Linux Mint 19.1 Cinnamon and used npm to install P3X OneNote. My title bar says I'm running v2019.4.5. System is updated and Chrome is my default browser. 

Everything is running well except for opening URLs in the app. Internal URLs stay within the app, as expected, but URLs in note content also stay within the app instead or opening in a browser. The app gets "stuck" in a quasi browser mode on these external pages, and requires a visit to **P3X OnceNote >> Corporate Home** to get back into OneNote. Even quitting the app and re-loading keeps thing on that last page. There's no "back" button or way to get out aside from going through **Corporate Home** again

I'm happy to provide any other info you might need.

**Comment by mospaw** [comment]
I like this solution. Thank you! 

Do you know when the automatic update might happen for my npm install? I loaded it on two different machines, quit out, and reloaded, but am still getting the old behavior. 

`npm update --dd` shows 0 modules to update.

**Comment by TheManFromEarth1** [comment]
I am stuck after clicking internal link, there is no back button.

P3X OneNote v2020.10.105, KDE

How can I clear cache?

**Comment by twms00** [comment]
Same issue as above - stuck on a login page - can't get back to notebooks.

**Comment by twms00** [comment]
Got it --

**Comment by lionelvoirol** [comment]
How did you escape from the browser in One Note? I am stuck on a webpage too and can't get back to P3X OneNote.

**Comment by jvlessa** [comment]
> How did you escape from the browser in One Note? I am stuck on a webpage too and can't get back to P3X OneNote.

Let me know if you find that out, because me too

**Comment by jvlessa** [comment]
> How did you escape from the browser in One Note? I am stuck on a webpage too and can't get back to P3X OneNote.

Press Alt
Then Click "Personal Note"

**Comment by Johschmidt43** [comment]
ALT does not do anything for me. Any help? I'm running OneNote on Ubuntu 20.10 (Groovy Gorilla).

**Comment by lionelvoirol** [comment]
Hey  Johschmidt43,
Hitting ALT on the version v2021.4.144 seems to work and show the menu when running on Ubuntu 20.04.
Best

**Comment by lionelvoirol** [comment]
Just installed the latest version. Works well we have by default the navigation bar. thanks.
