### ISSUE TITLE
Sandbox error Snap and AppImage

### ISSUE THREAD

**Issue by markfromarch** [patrikx3/onenote#63]
Hi.
Since the latest update (Arch Linux) I´m getting the following error by starting the App Image:

> 5785:0516/175703.623925:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_p3x-onaI53mY/chrome-sandbox is owned by root and has mode 4755.

Seems to be electron related?
Thank you in advance!
Regards.
Mark

**Comment by CeruleanWave** [comment]
I get the same error.  I tried uninstall and reinstall from snap.
When I try and open it, it crashes.  When i run it from CLI with sudo this is what I get.
`~$ sudo p3x-onenote
mkdir: cannot create directory '/run/user/0': Permission denied
ln: failed to create symbolic link '/root/snap/p3x-onenote/12/snap/p3x-onenote/12/Documents': No such file or directory
ln: failed to create symbolic link '/root/snap/p3x-onenote/12/snap/p3x-onenote/12/Desktop': No such file or directory
ln: failed to create symbolic link '/root/snap/p3x-onenote/12/snap/p3x-onenote/12/Downloads': No such file or directory
ln: failed to create symbolic link '/root/snap/p3x-onenote/12/snap/p3x-onenote/12/Music': No such file or directory
ln: failed to create symbolic link '/root/snap/p3x-onenote/12/snap/p3x-onenote/12/Pictures': No such file or directory
ln: failed to create symbolic link '/root/snap/p3x-onenote/12/snap/p3x-onenote/12/Videos': No such file or directory
ln: failed to create symbolic link '/root/snap/p3x-onenote/12/snap/p3x-onenote/12/Public': No such file or directory
ln: failed to create symbolic link '/root/snap/p3x-onenote/12/snap/p3x-onenote/12/Templates': No such file or directory`
I am running Kubuntu 19.04.

**Comment by markfromarch** [comment]
Sadly, not for me. But I think it´s an electron bug atm.  I used the appimage from day one and after the last (aur) updates it´s broken.
I´m on Arch Linux Kernel 5.1.2 with electron 4.1.4 and chrome 69.0.3497.128.
It seems like other users have the same problem (not with your app) but with electron. So maybe I have to wait, till the next electron update is up?

**Comment by markfromarch** [comment]
Found a workaround. Just run:
./p3x-onenote-2019.4.39-x86_64.AppImage **--no-sandbox**
Not perfect, but finally I can use my beloved app again! :-)

**Comment by markfromarch** [comment]
Perfect. Thank you!
