### ISSUE TITLE
EPERM error on startup

### ISSUE THREAD

**Issue by bpringe** [patrikx3/onenote#68]
I installed and ran it successfully at least once, but now when I try to open it, I get the following error.

![image](https://user-images.githubusercontent.com/12722744/60031710-d7a31600-966a-11e9-8a64-a94f7bcc146c.png)

Any idea how to fix this?

**Comment by kunalburgul** [comment]
Can you tell in more specific words, please?

**Comment by kunalburgul** [comment]
ok thanks

**Comment by bpringe** [comment]
Wow, thanks for the quick response/fix!
