### ISSUE TITLE
HTTP Basic Auth dialog not popping up

### ISSUE THREAD

**Issue by octaroot** [patrikx3/onenote#79]
Hi,

I'm having issues using P3X OneNote with my corporate account. Upon first launch, I got the classic Microsoft sign-in form. I've put in my corporate e-mail address and got redirected to my corporation's sign-in page. Normally, at that moment an HTTP Basic Auth dialog would pop up, but in the P3X OneNote app, it doesn't and I'm stuck on a white screen, with the loaded URL visible in the bottom purple bar.

Is there something I can do about this? Provide logs, perform the auth manually and transfer cookies/tokens etc?

**To reproduce:**

1) Try to go through a Microsoft sign in with the account `test@f-secure.com` via a browser
2) Observe an HTTP Basic Auth popup, abort the process
3) Try to sign in via the P3X OneNote app with the account `test@f-secure.com`
3) No HTTP Basic Auth dialog present, stuck on a white screen forever

Thanks for your support!

**Comment by shiolovesgod** [comment]
I have this same issue.  I can't authenticate with my corporate server.

**Comment by pawzlion** [comment]
> if you provide a corporate login i could probably fix it, but given i have no corporate access, it is impossible.

Do you have access to a university-provided Office365 account you can test with ? I'm having a similar problem. It shows me my university's own login screen... but it just doesn't accept the login. Works fine in Chrome.. doesn't work in this app.
