### ISSUE TITLE
Fresh install does not start

### ISSUE THREAD

**Issue by Alwinius** [patrikx3/onenote#91]
I installed the snap p3x-onenote from the stable channel today (v2020.4.115) on my Kubuntu 19.10. When I run it either from the launcher or on the command line, it justs exits with exit code 1. How can I provide more debug output?

**Comment by Alwinius** [comment]
Thanks for the quick reply. I still get an empty output. Other snaps work for me, but it might still be an issue with my installation. I remember there we some issues with file access previously.

**Comment by pinnerup** [comment]
I think I'm having the same problem. I'm running Ubuntu 19.10. I've install p3x-onenote running 'sudo snap install p3x-onenote'. When I run the program, it seems to work, but only the very first time. Subsequent runs just aren't effectuated, i.e. I get this:

```
pinnerup@ergi:~$ p3x-onenote 
pinnerup@ergi:~$ 
```
Nothing happens. Running 'ps aux | grep onenote' doesn't show any running process. 

I've tried deleting ~/snap/p3x-onenote/70/.config/configstore/p3x-onenote.json, but that doesn't seem to change everything.

Removing and the purging the snap, and then reinstalling, gives me the same result. Subsequent to a reinstall, the p3x-onenote will start once, but subsequent invocations seem ineffectual.
